name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    uses: ./.github/workflows/ci-backend.yml

  frontend:
    uses: ./.github/workflows/ci-frontend.yml